[RHCLOUD-30750] Moving to platform-middlware-go v2 package for identity and logging
RedHatInsights/insights-ingress-go pull request #388
Opened 2024-04-16 16:09 UTC by tahmidefaz

## What?
Explain what the change is linking any relevant JIRAs or Issues.

When moving to `platform-middlware-go v2`, changes were needed in `identity management`, `request_id fetching`, and `cloudwatch logging`.

## Why?
Consider what business or engineering goal does this PR achieves.

## How?
Describe how the change is implemented. Any noteable new libaries, APIs, or features.

## Testing
Did you add any tests for the change?

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-04-16 16:52 UTC, gmcculloug commented
Excited to see this PR.  Thanks @tahmidefaz 🙌

2024-04-16 18:25 UTC, tahmidefaz commented
/retest

2024-04-16 18:54 UTC, dehort requested changes
The changes look good to me, but it looks like the build is failing.

I can try to take a closer look at the failures later.

2024-04-16 18:59 UTC, tahmidefaz commented
> The changes look good to me, but it looks like the build is failing.
> 
> I can try to take a closer look at the failures later.

I was just looking into it, no error message. It just fails. :shrug: 
Maybe the build pipeline needs to be updated, not sure.

2024-04-18 15:39 UTC, skarekrow commented on unit_test.sh
> +echo | ls /opt/go
Don't forget to remove the debug :D

2024-04-19 12:48 UTC, merged